name: rate_the_beers
description: "An application for rating beers"
publish_to: 'none'

version: 1.0.0
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.19.0 <3.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # depend on the version that is shipped with the framework

  cupertino_icons: ^1.0.6

  http: ^1.1.2
  retry: ^3.1.2

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  async: ^2.11.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: any

  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true