name: rate_the_beers
description: "An application for rating beers"
publish_to: 'none'

version: 1.0.0
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.19.0 <3.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # depend on the version that is shipped with the framework

  cupertino_icons: ^1.0.6

  http: ^1.1.2
  retry: ^3.1.2
  flutter_cache_manager: ^3.3.2
  cached_network_image: ^3.3.1

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.1.2
  rxdart: ^0.27.7
  async: ^2.11.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: any

  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/google_fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/google_fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/google_fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/google_fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/google_fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/google_fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/google_fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/google_fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/google_fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
