name: Run lint
on: [ push, pull_request ]
jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          channel: 'stable'
      - run: flutter --version
      - name: Check format
        run: dart format lib --set-exit-if-changed --summary line -o none
      - run: flutter create . --platforms android
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - name: Run Lint
        run: flutter analyze